-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 7c003425b35fff516c0ee88f4040c8c208d474bd
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: flake8
-   repo: git@github.com:pre-commit/pre-commit
    sha: bcb1283267c0a041c77150a80a58f1bc2a3252d6
    hooks:
    -   id: validate_config
    -   id: validate_manifest
