-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 6343700aa063fe30acc319d2dc84353a35a3d6d0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E265,E309,E501
        - -v
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: flake8
-   repo: git@github.com:pre-commit/pre-commit
    sha: 3cac9489b3886f72b00f83d5128c2b22ea2fbcca
    hooks:
    -   id: validate_config
    -   id: validate_manifest
